### ISSUE TITLE
Search Result Reset

### ISSUE THREAD

**Issue by jbk68** [cortexrd/Knack-Toolkit-Library#180]
I have a scene in one of our apps that contains (2) tables both having a search field for data each contains.  Lately I've noticed that if I search in table 1 as an example "test1" any and all results are shown.  If I then try a search as an example "test2" in table 2, any and all results are shown.  **Now here's the problem**, if I hit the "reset" button next to the search field for table 1, it clears the entry (ie test1) and brings table back to normal just like it should but it will also clear the search bar for table 2 within the 10 seconds, which is what I have our auto refresh set to for both views.  The weird thing is, even though the data has been cleared in both search fields by me pressing the reset on table 1's search field, the reset button is still visible on the search field that wasn't pressed, in above example "table 2".  If I press reset button on table 2 search field,  reset button goes away.  

I've never noticed this before and didn't know if there was a change to KTL that is effecting this.  

Hoping there is a fix... JON

**Comment by CSWinnall** [comment]
Hi Jon

We will see if we can recreate this tomorrow.

Craig

**Comment by CSWinnall** [comment]
Hi Jon

This might be one for @cortexrd. I have replicated this issue (using KTL version 0.19.5). 
When we turned off the auto refresh this issue didn't occur.
Do you know when you started to see this issue @jbk68?

Craig

**Comment by jbk68** [comment]
Hey Craig, thanks for taking the time on this issue.  To answer your question, I just noticed it a few days ago but for all I know, it could have been that way for a while.  It's kind of unique for me to be using both search fields on the same view for various searches at the same time.  I do know however in the past I never saw this issue.

**Comment by cortexrd** [comment]
Hi guys,

This was a Knack bug.  You can see it by using the **Bypass KTL** feature from the Version Info Bar and **KTL Developer Tools** panel:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/42851359/3f58dfa7-30d3-4a61-a642-9249e15e49c9)

The bug is still there, without the KTL.

But the good news is that I've found a solution!
It will be in next release.

In the meantime you can test it by clicking **Debug this device** and OK (from same panel above).  This switches to the latest **"dev"** version of the KTL, before an official release, for testers.

To go back to normal, click the button again but Cancel this time.

Norm

**Comment by jbk68** [comment]
Hey Norm, I've also noticed another issue when using keyword _ar (my favorite ktl feature) with a view with a table that has multiple columns that requires the lower scroll bar.  

When the user is viewing a table that requires the use of the scroll bar, the table view will be reset when the page refreshes.  So if I have auto refresh set to 10 seconds and user is view data to the right side of table, table view resets and user has to scroll to the right again to view data only to be reset again in 10 seconds.  

If I remove keyword _ar, user can view data without the table view resetting and move back to the left.

Looking forward to your solution to initial issue with keyword _ar and hoping you have a solution to this issue I just posted.

Thanks... JON

**Comment by cortexrd** [comment]
Done - I have fixed this a moment ago.
Will be in next release.
Norm

**Comment by jbk68** [comment]
Thank you sir.  Look forward to the fix... JON

**Comment by cortexrd** [comment]
Released just now.  v0.21.2
Enjoy,
Norm

**Comment by jbk68** [comment]
Hey Norm, v021.2 appears to have fixed the scrolling issue using the keyword _ar, but it didn't fix the initial issue of this post of when there is multiple search field on a scene and user "reset" search criteria of one it still is resetting they other search fields and leaving the "reset" button on the second one cleared.

Not sure if this update was supposed to fix that.

Thank you for fixing the scrolling issues... JON

**Comment by cortexrd** [comment]
Here it works well.  Just tested again.
Can you give me access to a test page?
It may have something to do with the app style setting somewhere.

Norm

**Comment by jbk68** [comment]
Let me put one together and get back to you.

For security reasons, do you have an email I can sent link and credentials to?

**Comment by cortexrd** [comment]
Sure: **nd@ctrnd.com**
Norm
