### ISSUE TITLE
_dl doesnt appear to work

### ISSUE THREAD

**Issue by LeighBerrell** [cortexrd/Knack-Toolkit-Library#198]
I have a detail view on a public page that displays a phone number and email address, and I want to suppress the links on those fields.  I assumed that _dl used on that view would achieve that, but it doesn't seem to have any affect at all.   The view looks like this in the builder:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/156155161/071af8a0-eac5-4d3b-8b55-102bb7feaf18)

but like this in the live app, and the links are still active on those fields.

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/156155161/ce5161e9-73de-44d1-99a8-575335b130f5)

You can access this page here:
https://berrell.knack.com/cooldrive#quotes2/quote-details2/65a61c64452c8200283f2251/

Any assistance / ideas gratefully accepted.

**Comment by cortexrd** [comment]
Hi @LeighBerrell,

I was debugging your page, but then the link brought me to a login.  I guess you pulled the plug!?
Do you still have the issue?  Are you sure you don't have a syntax error in your console logs?

Norm

**Comment by LeighBerrell** [comment]
Sorry Norm @cortexrd,  I've been doing further work on this app and changed the name/path of the page without considering it would impact you.

try this link instead:  https://berrell.knack.com/cooldrive#quote-portal/quote/65a7aa5a2609900028bee284/

I checked console and see:  
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/156155161/83bc6137-86df-46e8-a328-3a28983be3e7)

Is this related? Given this is a no login public page?  I disabled my Adblock just in case it was that but made no difference

**Comment by LeighBerrell** [comment]
I just tried the same thing on a login secured page that displays the same detail view, and the links are still active, so it doesnt seem to be different whether its a login page or a public page.

**Comment by cortexrd** [comment]
@LeighBerrell,

I've just fixed the bug - thanks for reporting.
Try the **v0.22.4** please and let me know if all is ok.

BTW, the KTL's getPublicIP failed error you mentioned is not related.  It's just that I use an external web service (Cloudflare) to retrieve your public IP and you seem to be using uBlock Origin which prevents this from working.  But it has no negative impact other than that.

Norm

**Comment by LeighBerrell** [comment]
I have tried using the local debug option, but the issue appears to persist.  I’m not sure how to be selective on the version though, and I note that the version of KTL that’s loading is 22.5 in prod mode and 22.5-dev in debug  mode.  How do I select 22.4 ?

 



 

Rgds

 

Leigh Berrell

0412 100 045

**Comment by LeighBerrell** [comment]
I worked it out, still there with 0.22.4

 



 

Rgds

 

Leigh Berrell

0412 100 045

 

From: Leigh Berrell ***@***.***> 
Sent: Thursday, January 18, 2024 9:58 PM
To: 'cortexrd/Knack-Toolkit-Library' ***@***.***>
Subject: RE: [cortexrd/Knack-Toolkit-Library] _dl doesnt appear to work (Issue #198)

 

I have tried using the local debug option, but the issue appears to persist.  I’m not sure how to be selective on the version though, and I note that the version of KTL that’s loading is 22.5 in prod mode and 22.5-dev in debug  mode.  How do I select 22.4 ?

 



 

Rgds

 

Leigh Berrell

0412 100 045

**Comment by LeighBerrell** [comment]
I see included screen shots dont make it through from email replies.  Here is a screenshot again showing this still occurring with V0.22.4 

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/156155161/1ac5aa64-527c-441c-8fe6-1f49910a69e3)

**Comment by LeighBerrell** [comment]
I dont see any reference to KTL when I do that inspect, see below.

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/156155161/ab3af351-ab76-4992-bd7d-2fab6296f507)

and I dont see these errors in my console at all - all thats in the console is:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/156155161/8bc2b052-fe53-45a7-8e43-7597b73018a8)


I get the same outcome with right click in DEV mode as well, and a couple more comments on console but nothing related to what you show above.

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/156155161/dde632fd-4ca7-4d2a-aaf0-06dab28a97bd)

Its like the _dl isnt there, but here is the builder view showing the _dl in the titke if that view 302.

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/156155161/abe2eb38-4420-490b-b2d6-872b710465dd)

**Comment by LeighBerrell** [comment]
I tried _dl on another page, and it works perfectly there.  I'm wondering of the issue is that the page I specifically want this on has the header and menu hidden?  Could that somehow impact _dl ?   I'll try it without that difference.

**Comment by LeighBerrell** [comment]
Nope, isnt that. Damn.  I removed the CSS and javascript that was suppressing the header and back links, no difference.  Still working elsewhere but not on this specific page.

**Comment by LeighBerrell** [comment]
I created another view on that page with some link fields in it, and set it to _dl, but that view doesn't work either.  Something specific about this page.  Its not shown on the menu - could that be it?  ....  Nope  ... that made no difference.   There is now nothiing "different" about this page compared to others,  So I'm stumped as to why it works on other pages but not on this one.

Here is a link again. with extra view in it also not working:  https://berrell.knack.com/cooldrive#portal/quote/65a9c2355965540027402866/

**Comment by LeighBerrell** [comment]
@cortexrd just a thought - is it because these fields are CONNECTIONS from another table?

**Comment by LeighBerrell** [comment]
@cortexrd  Ok, Ive tried _dl on details views on a bunch of other pages as well.  Works on some, but doesnt work on others.  And I cant see any pattern as to why.   Plus I removed EVERY bit of javascript and CSS, except the 5 lines of the KTL loader, just in case its something in there but made no difference.   

I think for this specific issue I will just create two text fields for the email and phone number and fill them using record rules and display those fields.  

I'll leave a copy of the view with the link fields accessible on the page for a few more days in case you want to continue debugging.  Would be nice to know that _dl will work if I need it in the future.

**Comment by LeighBerrell** [comment]
Example where it works:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/156155161/a34c2817-f2b1-442e-8621-2fc483dc2344)


hit back link then go into same record and it doesnt work;

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/156155161/2601517e-49ee-4b33-84bc-d7bc5d386e77)

repeat 3 more time where it doesnt work.  then 4th time it works.

Nothing is showing up in the console in either case.

**Comment by cortexrd** [comment]
I think I know what's happening.  You did a good test!

Let me check this out tomorrow morning...
Norm

**Comment by cortexrd** [comment]
Actually... can you test the **dev** version please?
Norm

**Comment by LeighBerrell** [comment]
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/156155161/ae39a773-8db9-4aaa-a13c-7b7eb7de1b51)

Still see the issue with dev version.  Interestingly, it NEVER fails to work on a GRID view, but mostly fails to work on a DETAIL view.  You can see both above, one working and one not working.   (In this case, I could not get the detail view to work despite multiple refreshes etc).  Maybe its something specific to detail views?   This is the Builder showing those views, both with _dl in the title.

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/156155161/06fbb7be-fd23-4bcd-b21f-b0aab84c95d9)

**Comment by cortexrd** [comment]
Another test of dev please?  Do a Ctrl+F5 to bypass cache and get latest code.
ND

**Comment by LeighBerrell** [comment]
Now working!  Woohoo!

**Comment by cortexrd** [comment]
Great!!!

Now, I've removed a few extra lines of excessively safe code.
Can you test again?

Norm

**Comment by LeighBerrell** [comment]
Looks different when it renders now.  before it looked like KTL rendered first then Knack overwrote it. Now I see a "standard' render by Knack and then KTL removes the links. Interesting.

**Comment by cortexrd** [comment]
I added a delay to be sure.
But I removed it now to see if it's better.
Test again?

ND

**Comment by LeighBerrell** [comment]
Still working, and now it just renders immediately with no links - no hint of a "change".   All good.  Thanks!

**Comment by LeighBerrell** [comment]
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/156155161/dcd886d7-9b3a-4460-98fa-deeb7fe67c0d)

**Comment by cortexrd** [comment]
Great. I just released official **v0.22.7**.


Thanks for your tenacity :)

I guess we can close this now. 
If you see something else, just re-open.

Good night,
Norm
